[features]
seeds = false
skip-lint = false
[programs.localnet]
solanagifportalblockchainprogram = "411epjTUoVTbocyurmcHzUCcfem35iJ3F3yWQ3ytJZ7w"
[programs.devnet]
solanagifportalblockchainprogram = "411epjTUoVTbocyurmcHzUCcfem35iJ3F3yWQ3ytJZ7w"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "Localnet"
cluster = "devnet"
wallet = "/home/kali/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
